### ISSUE TITLE
Move data directory into Python package tree

### ISSUE THREAD

**Issue by weaverba137** [desihub/specter#34]
In order to work better with Anaconda environments, the data/ directory needs to be moved inside the Python package tree, *i.e.* to py/specter/data/.

**Comment by weaverba137** [comment]
@sbailey, I have a few questions about the data in the data directory.

1. data/sky/ZenExtinct-KNPO.fits is *only* referenced by dev/bigboss/bbthru.py.  That is, it is not used by the main specter package at all.  Can it be removed?
2. data/sky/sky-uves.fits is only used as an input in py/specter/test/test_binscripts.py.  Since it is only used for testing, can that be moved into the data/test directory (which would be moved somewhere inside py/specter/test)?

**Comment by sbailey** [comment]
specter/data could use a lot of cleaning up, in particular moving larger example files into a separate specter-example repo and perhaps even using the [BFG repo cleaner](https://rtyley.github.io/bfg-repo-cleaner/) to get them entirely out of the git history -- they predate me learning the downsides of keeping data-like files in git.

For now could you live with just moving data/ into the python directory structure to get it to work with `python setup.py install` and deal with cleanup/reorganization as a separate step?  i.e. let's fix what is *broken* first, and then separately cleanup.  The review prep is not affording me a lot of mental cycles for thinking about how this should really look post-cleanup...

**Comment by weaverba137** [comment]
Yes, I will concentrate on just moving the data, but keep this open as a reminder.
