### ISSUE TITLE
Bug in ex2d when filling diagonals of resolution matrix

### ISSUE THREAD

**Issue by julienguy** [desihub/specter#44]
In ex2d.py 
``` Rd[ispec-specmin, :, iwave+j-nlo] = Rx[j-ndiag:j+ndiag+1, j] ```

several occurrence of sub arrays Rd and Rx having different size when running
extraction with bundlesize = 1

**Comment by sbailey** [comment]
Julien put some test data at NERSC in /global/homes/j/jguy/specter_bug_data (though I need permissions to be updated to be able to see them...)

The failing command is
```
desi_extract_spectra -i preproc-00000111.fits -p psf-specex-CCDS1R.fits  \
  --bundlesize 1 -w 5620.,7730.,1. -o frame-spectroperf-00000111.fits
```
